### ISSUE TITLE
How to determine if Dymo Connect or Dymo Label is in use

### ISSUE THREAD

**Issue by StewPoll** [dymosoftware/dymo-connect-framework#1]
Hi there.

I can see the `label.isDCDLabel()` and `label.isDLSLabel()` functions are available to use to validate if the labels will work with the chosen piece of software, but is there a way to see which of the programs is installed?

Or is that covered in the `dymo.label.framework.checkEnvironment()` function?

**Comment by dymosoftware** [comment]
Hi @StewPoll, unfortunately, there is no function to determine which software is running.
Making a request to http://127.0.0.1:41951/api/addin/checkApiStatus, if you are able to get answer, it means DYMO Connect Software is running.
