### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by StewPoll** [dymosoftware/dymo-connect-framework#2]
Just wondering if you could add a License, such as the MIT license, to this repo, so that any potential copyright issues are avoided from using this software.

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by grezniczek** [comment]
Yes, this would be very helpful. I guess DYMO lives from selling their printers and supplies, so it seems to be in their best interest to have this used as widely as possible. MIT would be a good license.

**Comment by dymosoftware** [comment]
License file has been added.
