### ISSUE TITLE
Multiline text-object causes freeze/crash

### ISSUE THREAD

**Issue by mbmleone** [dymosoftware/dymo-connect-framework#26]
Today we found a serious issue with Dymo Connect templates.
They can cause a freeze with eventually a crash.

This happens in the following situation:
- Dymo Connect 10.3.2.18
- Template with multiline text object - like for example template in [example.zip](https://github.com/dymosoftware/dymo-connect-framework/files/7161342/example.zip)
- Using the framework you call label.getObjectText(name) with name gotten from label.getObjectNames()
- Issue doesn't happen when text object is limited to single line.

What happens is this:

1. First the website freeze and makes it impossible to do anything.
2. Then after a long time it resumes and shows this error in console:
```
Uncaught InternalError: allocation size overflow
    _getAddressObjectText
```
3. Nothing is printed by the Dymo printer.

Can this please be investigated and fixed?
Thanks!

**Comment by giuliodamato** [comment]
Hi @mbmleone,
I found the bug and fixed it 😂

The freeze is originated by a nested for loop that tragically overwrites the control variable of its parent 🤦‍♂️

https://github.com/dymosoftware/dymo-connect-framework/blob/1bf94721c5c9dcc74a13bb4f984ac488381942e4/dymo.connect.framework.js#L10432

Changing the loop to this solves the problem:
```
for (gz = 0; gz < n.length; gz++)
{
  var i = dymo.xml.getElement(n[gz], "Text");
  o += dymo.xml.getElementText(i)
}
```

I'll release the fix in my repo tomorrow 😉

@dymosoftware: I really deserve some gadgets now 😂

**Comment by giuliodamato** [comment]
The fixed version is in my repo, please check it out and confirm us that it actually works.
https://github.com/giuliodamato/dymo-connect-framework

The version in the repo also fixes issue #13.

**Comment by mbmleone** [comment]
Thanks for the fixed release.
We just checked it and it indeed fixes the issue!
Thanks again!

**Comment by mbmleone** [comment]
We just discovered this causes line breaks to disappear.
Please make sure the line breaks are added inside the loop.
