### ISSUE TITLE
Unable to set which side to print on TwinTurbo

### ISSUE THREAD

**Issue by zrs67929** [dymosoftware/dymo-connect-framework#4]
When declaring which side to print from If a computer has the Dymo connect software (DCD) installed it prints from the right side regardless of printer properties. Works fine if printing from a computer using  Dymo Label (DLS).

Relevant snippets of code that prints on the right side only with DCD:

		var label = dymo.label.framework.openLabelXml(labelXml);             
		var printParams= {};
		printParams.twinTurboRoll = dymo.label.framework.TwinTurboRoll.Left;

                // select printer to print on
                // for simplicity sake just use the first LabelWriter printer
                var printers = dymo.label.framework.getPrinters();
                if (printers.length == 0)
                    throw "No DYMO printers are installed or the webservice is not running";

                var printerName = "";
                for (var i = 0; i < printers.length; ++i)
                {
                    var printer = printers[i];
                    if (printer.printerType == "LabelWriterPrinter")
                    {
                        printerName = printer.name;
                        break;
                    }
                }
                
                if (printerName == "")
                    throw "No LabelWriter printers found. Install LabelWriter printer";

                // finally print the label
                label.print(printerName, dymo.label.framework.createLabelWriterPrintParamsXml(printParams));

**Comment by dymosoftware** [comment]
> When declaring which side to print from If a computer has the Dymo connect software (DCD) installed it prints from the right side regardless of printer properties. Works fine if printing from a computer using Dymo Label (DLS).
> 
> Relevant snippets of code that prints on the right side only with DCD:
> 
> ```
> 	var label = dymo.label.framework.openLabelXml(labelXml);             
> 	var printParams= {};
> 	printParams.twinTurboRoll = dymo.label.framework.TwinTurboRoll.Left;
> 
>             // select printer to print on
>             // for simplicity sake just use the first LabelWriter printer
>             var printers = dymo.label.framework.getPrinters();
>             if (printers.length == 0)
>                 throw "No DYMO printers are installed or the webservice is not running";
> 
>             var printerName = "";
>             for (var i = 0; i < printers.length; ++i)
>             {
>                 var printer = printers[i];
>                 if (printer.printerType == "LabelWriterPrinter")
>                 {
>                     printerName = printer.name;
>                     break;
>                 }
>             }
>             
>             if (printerName == "")
>                 throw "No LabelWriter printers found. Install LabelWriter printer";
> 
>             // finally print the label
>             label.print(printerName, dymo.label.framework.createLabelWriterPrintParamsXml(printParams));
> ```

Hi @zrs67929, this is a bug reported on web service.This issue will be fixed in a new release of DYMO Connect in a few weeks.

**Comment by zrs67929** [comment]
Thank you for the update!
Some more details after further testing: It seems that it behaves like TwinTurboRoll.auto and setting left or right has no effect. 

Also we noticed some font size inconsistencies with labels created in DSL but printed with the DCD web service. (Suspicion is that it has to do with shrink to fit or auto fit but haven't testing it enough) We are trying to keep backward compatibility because our software is used on thousands of client computers and we can't update them all at once.

Is there any way we could get beta versions of future releases? Clients have updated the software on their own and this has cause hours of troubleshooting with them. We can't test compatibility ahead of time. We advise them to only use versions of software we've tested, but DLS is no longer a link on your website.

**Comment by dymosoftware** [comment]
Yes, exactly that is the issue with TwinTurboRoll that will be fixed in the next release of DCD.
DCD Web Service implements the same render as DYMO Connect Software, so labels created from DLS and printed from DCD could mismatch the style.
I would recommend you, once you are ready to use DCD Web service through your applications then migrate your DLS labels to DCD labels to avoid these differences.
We don't have a way to distribute beta versions of DCD.
Latest version of DLS is available from this [link](https://www.dymo.com/en-US/dymo-label-software-v873-windows#tab=Support).

Important: 
1.- DCD v1.2 will override DLS web service, so make sure to uninstall DCD if you want to go back to DLS.
2.- DLS Windows is no longer supported, we won't release new versions, features or bug fixes.

**Comment by zrs67929** [comment]
Thank you for the information! Will DCD be released for Mac in the future? We currently tell customers that they can use Windows or Mac computers.

This is what we understand so far:
Labels created in DCD will NOT print in DLS.
Mac does not have DCD.
DCD prints name badges/ receipts that are not usable if created in DSL. (barcode and font sizing issue)
DLS is not supported for Windows anymore.

So my question/request is: 
Is there a way for us to either call a javascript function (or make our own) to determine if DCD or DSL is running? It sounds to me like we will have to maintain two different versions of our name badges/receipts until we can transition all our customers over to DCD and it is available for Macs.

We are very thankful that the dymo connect framework still works with DSL though! Thank you!

**Comment by dymosoftware** [comment]
Yes, DCD for Mac is in process so far only DLS Mac is available.
If you install DLS on Windows you have to know that we will not offer new releases or bug fixes for this.
Some paper names(SKU) from DLS are not supported on DCD.
There is no function from JS to determine whether DCD or DLS is running but take a look to this [thread](https://github.com/dymosoftware/dymo-connect-framework/issues/1#issuecomment-585336264).

**Comment by dymosoftware** [comment]
@zrs67929 DCD 1.3.1 has been released and includes a fix for Twin Turbo roll. You can download DCD from https://www.dymo.com/en-US/online-support/dymo-user-guides.
