### ISSUE TITLE
DYMO Connect SDK 1.4.3.10-beta: Referencing TextObject names

### ISSUE THREAD

**Issue by SRA-DE** [dymosoftware/dymo-connect-framework#53]
A "*.dymo" label is designed with 12 text objects. These text objects are named with "FolderText" and "Folder", "OrderText" and "Order", "MaterialText" and "Material", "OffsetText" and "Offset", "AngleText" and "Angle", "DateText" and "Date". 

The "...Text" objects are used to print the description in different languages for international customers. The other objects will be filled with data content.

The text object replacement is coded as:
DymoLabelField = Program.DM.DYMOConnectLabel.GetLabelObject("FolderText");
if (DymoLabelField != null)
    Program.DM.DYMOConnectLabel.UpdateLabelObject(DymoLabelField, "FolderText1");
DymoLabelField = Program.DM.DYMOConnectLabel.GetLabelObject("Folder");
if (DymoLabelField != null)
    Program.DM.DYMOConnectLabel.UpdateLabelObject(DymoLabelField, "Folder1");
DymoLabelField = Program.DM.DYMOConnectLabel.GetLabelObject("JobText");
if (DymoLabelField != null)
    Program.DM.DYMOConnectLabel.UpdateLabelObject(DymoLabelField, "JobText1");
DymoLabelField = Program.DM.DYMOConnectLabel.GetLabelObject("Job");
if (DymoLabelField != null)
    Program.DM.DYMOConnectLabel.UpdateLabelObject(DymoLabelField, "Job1");
...

The issue:
If searching for text object "Folder", the SDK is referencing and replacing the "FolderText" object.
If searching for text object "Job", the SDK is referencing and replacing the "JobText" object.
...

Find a sample label "eCAB0A6.DYMO" attached:
[eCAB0A6_DYMO.zip](https://github.com/dymosoftware/dymo-connect-framework/files/8152513/eCAB0A6_DYMO.zip)

Thanks and regards.

**Comment by dymosoftware** [comment]
DYMO SDK provide the first label object from IEnumerableCollection for the performance.
Can you rename Folder to something else like "FolderName"?

Thank you,

**Comment by SRA-DE** [comment]
That was my workaround: Using "FolderText" and "FolderContent" instead of "Folder".

But it would be nice, to have exact seach results eventually. This will reduce questions of our customers ;-)

Thanks.

**Comment by dymosoftware** [comment]
I will add this improvement into back log and bring it up to our team.
Thank you.

**Comment by SRA-DE** [comment]
Great support.

Thanks a lot!

**Comment by dymosoftware** [comment]
I added log and brought it our team and everyone liked to provide the fix.
Thank you.

**Comment by dymosoftware** [comment]
I will close this issue because we pushed a code fix for this defect in the next release.
Thank you.
