### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by fulldecent** [dymosoftware/dymo-connect-framework#62]
This link in the readme is broken

https://github.com/dymosoftware/dymo-connect-framework/blob/master/dymo.connect.framework.js

**Comment by dymosoftware** [comment]
The link is fixed.
Thank you for your found and time.

**Comment by timint** [comment]
@dymosoftware Just a word a of advice. This is when you close the open issue ticket.

The fix is referenced here:
https://github.com/dymosoftware/dymo-connect-framework/commit/4d3220a1a7287317cc77bb67a30b8367bd3ee516

**Comment by fulldecent** [comment]
Thank you, looks good

**Comment by timint** [comment]
@fulldecent :) I didn't mean for you to close it. Project management is terrible in this repo. They should step up or leave it to someone else.
