### ISSUE TITLE
Cannot render label dymo connect

### ISSUE THREAD

**Issue by Malkai99** [dymosoftware/dymo-connect-framework#8]
Hi there!, im using dymo framework for first time, im using the dymo connect software to create the label, the problem here its is i cannot use the method render or print of the ILabel object that i get of using openLabelXml, i check is a valid label, and i get true, this is the error i get: 
![error dymo](https://user-images.githubusercontent.com/26637854/93113172-78219380-f67e-11ea-92c8-766fe5e7bcbd.png)

I check the label and it opens in the dymo connect, i dont think the label has a problem, so i decide to use the renderLabel method, and it get render, but when i set text on a textObject, it change it, but when i render again, the label it have the same text before the set, and when i try to print it the same error pops.

I try with a label of the other software (the dls version) and it works fine with ILabel methods, so i dont know if im doing it wrong, or is it an error on the framework. Thank you!

**Comment by yasnaderi** [comment]
The same problem as yours

**Comment by yasnaderi** [comment]
> Hi there!, im using dymo framework for first time, im using the dymo connect software to create the label, the problem here its is i cannot use the method render or print of the ILabel object that i get of using openLabelXml, i check is a valid label, and i get true, this is the error i get:
> ![error dymo](https://user-images.githubusercontent.com/26637854/93113172-78219380-f67e-11ea-92c8-766fe5e7bcbd.png)
> 
> I check the label and it opens in the dymo connect, i dont think the label has a problem, so i decide to use the renderLabel method, and it get render, but when i set text on a textObject, it change it, but when i render again, the label it have the same text before the set, and when i try to print it the same error pops.
> 
> I try with a label of the other software (the dls version) and it works fine with ILabel methods, so i dont know if im doing it wrong, or is it an error on the framework. Thank you!

I think the JS library is not compatible with the 1.x version of demo connect.

**Comment by dymosoftware** [comment]
Hi @Malkai99 and @yasnaderi,
DYMO.Connect.Framework needs DYMO Connect v1.2 at least to be able to open, update, and print labels created from DYMO Connect. It has the same functions of the old DYMO.Label.Framework; therefore, it works with DLS installed as well with an exception. See the follow scenarios:

**DYMO.Connect.Framework works**

Opening a label created from DLS with DLS Service running.
Opening a label created from DLS with DCD Service running.
Opening a label created from DCD with DCD Service running.

**DYMO.Connect.Framework _does not work_**

Opening a label created from DCD with DLS Service running.

Could you attach your label file? To validate the error with our team.

**Comment by dymosoftware** [comment]
Somehow the HTTP request from web browser was changing the end tag of the Color element.
Adding a space between start and end tag will fix the issue. 
`<Color A="1" R="0" G="0" B="0">[HERE ADD A SPACE]</Color>`
