### ISSUE TITLE
Feature Request: serial number or a unique identifier 

### ISSUE THREAD

**Issue by stormframe** [dymosoftware/dymo-connect-framework#9]
Hello developer team,
would it be possible to read out the serial number or a unique identifier of the printer using the JS Framework?

Thus different labels could be inserted in 2 or 3 printers. The correct printer is activated using the serial number.

**Comment by stormframe** [comment]
Is there a way to include this feature?

**Comment by dymosoftware** [comment]
Hi, unfortunately  is not possible to add this feature to JS FWK since DLS and DYMO Connect have not the ability to return such value. We'll keep it in mind for further releases.

**Comment by stormframe** [comment]
Thanks for the answer. Maybe it will come. Is there a way to send this request to Dymo? Do you know a contact here?

**Comment by dymosoftware** [comment]
Yes, @stormframe you can send your request to dymoconsumercare@newellco.com.
